In [58]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

digits = load_digits()

In [59]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [60]:
X_train

array([[ 0.,  0.,  0., ...,  4.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  6.,  0.,  0.],
       ...,
       [ 0.,  0.,  8., ...,  3.,  0.,  0.],
       [ 0.,  0.,  2., ..., 15.,  4.,  0.],
       [ 0.,  0.,  2., ...,  1.,  0.,  0.]])

Using Logistic Regression

In [61]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

d:\developments\ML and DL\CodeBasics_ML_PlayList\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

Using Support Vector Machine(SVM)

In [62]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9944444444444445

Using Random Forest Classifier

In [63]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975925925925926

K_Fold_Cross_Validation using for split the original data set into sub data sets and per each data set it bring the score of the model, more formally it  is used to verifing the performace of the models

In [64]:
from sklearn.model_selection import KFold

#  number of split data set
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [65]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [66]:
# moduler format to fit and get the model score
def get_score(model, X_train,X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [67]:
# StratifiedKFold is little better than KFold, but why? and StratifiedKFold requred to argument for split
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [74]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, y_train, y_test))

d:\developments\ML and DL\CodeBasics_ML_PlayList\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\developments\ML and DL\CodeBasics_ML_PlayList\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

In [69]:
scores_l

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [70]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [75]:
scores_rf

[0.9315525876460768, 0.9549248747913188, 0.9215358931552587]

In [76]:
# You don't need to wirte a lot of codes like adove, instead you can use cross_val_score
from sklearn.model_selection import cross_val_score 

In [78]:
#  CV = n_splits
cross_val_score(LogisticRegression(), digits.data, digits.target, cv=3)

d:\developments\ML and DL\CodeBasics_ML_PlayList\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\developments\ML and DL\CodeBasics_ML_PlayList\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92153589, 0.94156928, 0.91652755])

In [79]:
cross_val_score(SVC(), digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [80]:
cross_val_score(RandomForestClassifier(n_estimators=50),
                digits.data, digits.target, cv=3)

array([0.95158598, 0.95993322, 0.92821369])